# Site settings
title: Shweta Soundararajan
description: NLP Researcher | PhD from Technological University Dublin | Responsible AI & Large Language Models
repository: shwetarajan03/shwetarajan03.github.io

# User settings
author:
  name: Shweta Soundararajan
  bio: NLP Researcher with focus on Responsible AI and Large Language Models
  scholar_userid: o4k-5I8AAAAJ
  googlescholar: https://scholar.google.com/citations?user=o4k-5I8AAAAJ&hl=en
  github_username: shwetarajan03
  linkedin_username: shwetarajan03
  avatar: 
  uri: https://shwetarajan03.github.io

# Site settings
url: "https://shwetarajan03.github.io"
baseurl: ""

# Language settings
lang: en

# Google Analytics
google_analytics_id: 

# Markdown Settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Exclude from processing
exclude:
  - .jekyll-cache/
  - .sass-cache/
  - '*.gemspec'
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Keep files
keep_files:
  - CNAME
  - .nojekyll
  - .git
